### ISSUE TITLE
No module named factories #

### ISSUE THREAD

**Issue by ordinc** [mikemalinowski/crab#1]
I followed https://github.com/mikemalinowski/factories, pip installed the factories, I also cloned the zip, but still prompted the error crab\core.py line 26: No module named factories #
Python version 3.7
Maya version 2018.4

**Comment by mikemalinowski** [comment]
Ah, that is probably a sys.path issue with where maya is looking. I will look at embedding factories into crab to remove the external dependency. I'll post once i get that added.

**Comment by mikemalinowski** [comment]
This has now been done - all the module dependencies have been included within the crab package. Its now a case of putting the crab folder into the maya scripts folder then running ...

import crab
crab.creator.launch()

If you get any dependency issues let me know
