### ISSUE TITLE
Minor: Unhandled exception if no meta is found.

### ISSUE THREAD

**Issue by ldunham1** [mikemalinowski/crab#3]
https://github.com/mikemalinowski/crab/blob/52a87c2c10fdf5a9c40706a1bdabc72bdf2aee2a/crab/core.py#L249

An AttributeType exception will be raised if None is returned by meta() (by design).
Where possible, it might be safer to wrap in a try: except AttributeError: to better handle existing implementation.

**Comment by mikemalinowski** [comment]
Added a try except as per your suggest. Done it for all four accessors.
